import time
import tarfile
import io
from typing import Dict
from .models import ModuleSpec


class ModuleCreator:
    @staticmethod
    def _escape_py(s: str) -> str:
        return s.replace('"', '\\"').replace("'", "\\'")

    @classmethod
    def generate_python(cls, spec: ModuleSpec) -> Dict[str, str]:
        pkg = spec.name.replace("-", "_")
        voice_id = cls._escape_py(spec.voice_id)
        model = cls._escape_py(spec.model)
        persona = cls._escape_py(spec.persona_name)
        desc = cls._escape_py(spec.description or f"{spec.persona_name} voice synthesis module")

        files = {}
        files[f"{pkg}/__init__.py"] = (
            f'"""{spec.name}: {desc}\n'
            f'Auto-generated by Voice Synthesis Module Creator\n"""\n\n'
            f'__version__ = "0.1.0"\n__author__ = "{spec.author}"\n\n'
            f"from .client import {persona}Voice, {persona}Client\n\n"
            f'__all__ = ["{persona}Voice", "{persona}Client"]\n'
        )

        files[f"{pkg}/client.py"] = f'''import os
from typing import Optional, BinaryIO

try:
    from fish_voice import FishVoiceClient
except ImportError:
    raise ImportError("Install fish_voice first: pip install fish-voice")

DEFAULT_VOICE_ID = "{voice_id}"
DEFAULT_MODEL = "{model}"


class {persona}Client(FishVoiceClient):
    """Synthesizer pre-configured for {persona} voice."""

    def __init__(self, api_key: Optional[str] = None, **kwargs):
        key = api_key or os.getenv("FISH_API_KEY", "")
        super().__init__(api_key=key, **kwargs)
        self.default_voice_id = DEFAULT_VOICE_ID
        self.default_model = DEFAULT_MODEL


class {persona}Voice:
    """Convenience wrapper for {persona} voice generation."""

    VOICE_ID = DEFAULT_VOICE_ID
    MODEL = DEFAULT_MODEL

    def __init__(self, client: Optional["{persona}Client"] = None):
        self.client = client or {persona}Client()

    def synthesize(self, text: str, **kwargs) -> bytes:
        """Generate audio bytes from text."""
        return self.client.synthesize(
            text, voice_id=self.VOICE_ID, model=self.MODEL, **kwargs
        )

    def synthesize_to_file(self, text: str, path: str, **kwargs) -> None:
        """Save synthesized audio directly to file."""
        data = self.synthesize(text, **kwargs)
        with open(path, "wb") as f:
            f.write(data)
'''

        files["pyproject.toml"] = f'''[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{spec.name}"
version = "0.1.0"
authors = [{{ name = "{spec.author}" }}]
description = "{desc}"
requires-python = ">=3.10"
dependencies = ["fish-voice>=0.2.0"]

[project.scripts]
{spec.name} = "{pkg}.cli:main"
'''

        if spec.include_cli:
            files[f"{pkg}/cli.py"] = f'''import sys
import argparse
from .client import {persona}Voice


def main():
    p = argparse.ArgumentParser(description="Generate {persona} voice")
    p.add_argument("text", help="Text to speak")
    p.add_argument("-o", "--output", default="output.mp3")
    args = p.parse_args()

    voice = {persona}Voice()
    try:
        voice.synthesize_to_file(args.text, args.output)
        print(f"[OK] Saved to {{args.output}}")
    except Exception as e:
        print(f"[ERROR] {{e}}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
'''
            files[f"{pkg}/__main__.py"] = "from .cli import main\nmain()\n"

        files["README.md"] = f'''# {spec.name}

{desc}

## Quickstart

```bash
export FISH_API_KEY="your-key"
pip install .
{spec.name} "Hello from {persona}!" -o hello.mp3
```
'''
        return files

    @classmethod
    def generate_node(cls, spec: ModuleSpec) -> Dict[str, str]:
        pkg_name = spec.name
        voice_id = spec.voice_id
        model = spec.model
        persona = spec.persona_name

        files = {
            "package.json": f'''{{
  "name": "{pkg_name}",
  "version": "0.1.0",
  "main": "index.js",
  "bin": {{ "{pkg_name}": "cli.js" }},
  "dependencies": {{}}
}}''',
            "index.js": f'''const FISH_API = "https://api.fish.audio/v1/tts";

const DEFAULT_VOICE_ID = "{voice_id}";
const DEFAULT_MODEL = "{model}";

class {persona}Voice {{
  constructor(apiKey) {{
    this.apiKey = apiKey || process.env.FISH_API_KEY;
    this.voiceId = DEFAULT_VOICE_ID;
    this.model = DEFAULT_MODEL;
  }}

  async synthesize(text) {{
    const res = await fetch(FISH_API, {{
      method: "POST",
      headers: {{
        "Authorization": `Bearer ${{this.apiKey}}`,
        "Content-Type": "application/json"
      }},
      body: JSON.stringify({{
        text, voice_id: this.voiceId, model: this.model, response_format: "mp3"
      }})
    }});
    if (!res.ok) throw new Error(`API error: ${{res.status}}`);
    return new Uint8Array(await res.arrayBuffer());
  }}
}}

module.exports = {{ {persona}Voice }};
''',
            "cli.js": f'''#!/usr/bin/env node
const {{ {persona}Voice }} = require("./index");
const fs = require("fs");

async function main() {{
  const text = process.argv.slice(2).join(" ");
  if (!text) {{ console.error("Usage: {pkg_name} \\"text\\" [-o out.mp3]"); process.exit(1); }}
  const outIdx = process.argv.indexOf("-o");
  const out = outIdx > -1 ? process.argv[outIdx + 1] : "output.mp3";
  const voice = new {persona}Voice();
  const audio = await voice.synthesize(text);
  fs.writeFileSync(out, Buffer.from(audio));
  console.log("[OK] Saved to", out);
}}
main().catch(e => {{ console.error("[ERROR]", e.message); process.exit(1); }});
''',
            "README.md": f"# {pkg_name}\nPreconfigured {persona} voice module.\nSee index.js for usage.\n",
        }
        return files

    @classmethod
    def create_archive(cls, files: Dict[str, str]) -> bytes:
        """Pack all files into a .tar.gz in memory."""
        buf = io.BytesIO()
        with tarfile.open(fileobj=buf, mode="w:gz") as tar:
            for path, content in files.items():
                data = content.encode("utf-8")
                info = tarfile.TarInfo(name=path)
                info.size = len(data)
                info.mtime = int(time.time())
                tar.addfile(info, io.BytesIO(data))
        return buf.getvalue()
